repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: flake8
    -   id: detect-private-key
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-yaml
